// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ad.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Expiration    int64                  `protobuf:"varint,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_proto_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ad) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Ad) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type AdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdRequest) Reset() {
	*x = AdRequest{}
	mi := &file_proto_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdRequest) ProtoMessage() {}

func (x *AdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdRequest.ProtoReflect.Descriptor instead.
func (*AdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{1}
}

func (x *AdRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type AdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdResponse) Reset() {
	*x = AdResponse{}
	mi := &file_proto_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdResponse) ProtoMessage() {}

func (x *AdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdResponse.ProtoReflect.Descriptor instead.
func (*AdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{2}
}

func (x *AdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_proto_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAdRequest) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_proto_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_proto_ad_proto protoreflect.FileDescriptor

const file_proto_ad_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ad.proto\x12\x02ad\"\x82\x01\n" +
	"\x02Ad\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"expiration\x18\x05 \x01(\x03R\n" +
	"expiration\"\x1f\n" +
	"\tAdRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"$\n" +
	"\n" +
	"AdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\")\n" +
	"\x0fCreateAdRequest\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"&\n" +
	"\x10CreateAdResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid2\x95\x01\n" +
	"\tAdService\x125\n" +
	"\bCreateAd\x12\x13.ad.CreateAdRequest\x1a\x14.ad.CreateAdResponse\x12'\n" +
	"\x06ReadAd\x12\r.ad.AdRequest\x1a\x0e.ad.AdResponse\x12(\n" +
	"\aServeAd\x12\r.ad.AdRequest\x1a\x0e.ad.AdResponseB'Z%github.com/killiankopp/arago/ad/protob\x06proto3"

var (
	file_proto_ad_proto_rawDescOnce sync.Once
	file_proto_ad_proto_rawDescData []byte
)

func file_proto_ad_proto_rawDescGZIP() []byte {
	file_proto_ad_proto_rawDescOnce.Do(func() {
		file_proto_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ad_proto_rawDesc), len(file_proto_ad_proto_rawDesc)))
	})
	return file_proto_ad_proto_rawDescData
}

var file_proto_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ad_proto_goTypes = []any{
	(*Ad)(nil),               // 0: ad.Ad
	(*AdRequest)(nil),        // 1: ad.AdRequest
	(*AdResponse)(nil),       // 2: ad.AdResponse
	(*CreateAdRequest)(nil),  // 3: ad.CreateAdRequest
	(*CreateAdResponse)(nil), // 4: ad.CreateAdResponse
}
var file_proto_ad_proto_depIdxs = []int32{
	0, // 0: ad.AdResponse.ad:type_name -> ad.Ad
	0, // 1: ad.CreateAdRequest.ad:type_name -> ad.Ad
	3, // 2: ad.AdService.CreateAd:input_type -> ad.CreateAdRequest
	1, // 3: ad.AdService.ReadAd:input_type -> ad.AdRequest
	1, // 4: ad.AdService.ServeAd:input_type -> ad.AdRequest
	4, // 5: ad.AdService.CreateAd:output_type -> ad.CreateAdResponse
	2, // 6: ad.AdService.ReadAd:output_type -> ad.AdResponse
	2, // 7: ad.AdService.ServeAd:output_type -> ad.AdResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ad_proto_init() }
func file_proto_ad_proto_init() {
	if File_proto_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ad_proto_rawDesc), len(file_proto_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ad_proto_goTypes,
		DependencyIndexes: file_proto_ad_proto_depIdxs,
		MessageInfos:      file_proto_ad_proto_msgTypes,
	}.Build()
	File_proto_ad_proto = out.File
	file_proto_ad_proto_goTypes = nil
	file_proto_ad_proto_depIdxs = nil
}
