// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tracker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdImpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdUuid        string                 `protobuf:"bytes,1,opt,name=ad_uuid,json=adUuid,proto3" json:"ad_uuid,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // New field for timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdImpression) Reset() {
	*x = AdImpression{}
	mi := &file_proto_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdImpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdImpression) ProtoMessage() {}

func (x *AdImpression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdImpression.ProtoReflect.Descriptor instead.
func (*AdImpression) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *AdImpression) GetAdUuid() string {
	if x != nil {
		return x.AdUuid
	}
	return ""
}

func (x *AdImpression) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AdImpression) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateImpressionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdUuid        string                 `protobuf:"bytes,1,opt,name=ad_uuid,json=adUuid,proto3" json:"ad_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImpressionRequest) Reset() {
	*x = UpdateImpressionRequest{}
	mi := &file_proto_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImpressionRequest) ProtoMessage() {}

func (x *UpdateImpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImpressionRequest.ProtoReflect.Descriptor instead.
func (*UpdateImpressionRequest) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateImpressionRequest) GetAdUuid() string {
	if x != nil {
		return x.AdUuid
	}
	return ""
}

type UpdateImpressionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImpressionResponse) Reset() {
	*x = UpdateImpressionResponse{}
	mi := &file_proto_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImpressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImpressionResponse) ProtoMessage() {}

func (x *UpdateImpressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImpressionResponse.ProtoReflect.Descriptor instead.
func (*UpdateImpressionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateImpressionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetImpressionCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdUuid        string                 `protobuf:"bytes,1,opt,name=ad_uuid,json=adUuid,proto3" json:"ad_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImpressionCountRequest) Reset() {
	*x = GetImpressionCountRequest{}
	mi := &file_proto_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImpressionCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImpressionCountRequest) ProtoMessage() {}

func (x *GetImpressionCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImpressionCountRequest.ProtoReflect.Descriptor instead.
func (*GetImpressionCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *GetImpressionCountRequest) GetAdUuid() string {
	if x != nil {
		return x.AdUuid
	}
	return ""
}

type GetImpressionCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdUuid        string                 `protobuf:"bytes,1,opt,name=ad_uuid,json=adUuid,proto3" json:"ad_uuid,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImpressionCountResponse) Reset() {
	*x = GetImpressionCountResponse{}
	mi := &file_proto_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImpressionCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImpressionCountResponse) ProtoMessage() {}

func (x *GetImpressionCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImpressionCountResponse.ProtoReflect.Descriptor instead.
func (*GetImpressionCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *GetImpressionCountResponse) GetAdUuid() string {
	if x != nil {
		return x.AdUuid
	}
	return ""
}

func (x *GetImpressionCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_tracker_proto protoreflect.FileDescriptor

const file_proto_tracker_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tracker.proto\x12\atracker\"[\n" +
	"\fAdImpression\x12\x17\n" +
	"\aad_uuid\x18\x01 \x01(\tR\x06adUuid\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"2\n" +
	"\x17UpdateImpressionRequest\x12\x17\n" +
	"\aad_uuid\x18\x01 \x01(\tR\x06adUuid\"4\n" +
	"\x18UpdateImpressionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x19GetImpressionCountRequest\x12\x17\n" +
	"\aad_uuid\x18\x01 \x01(\tR\x06adUuid\"K\n" +
	"\x1aGetImpressionCountResponse\x12\x17\n" +
	"\aad_uuid\x18\x01 \x01(\tR\x06adUuid\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xc8\x01\n" +
	"\x0eTrackerService\x12W\n" +
	"\x10UpdateImpression\x12 .tracker.UpdateImpressionRequest\x1a!.tracker.UpdateImpressionResponse\x12]\n" +
	"\x12GetImpressionCount\x12\".tracker.GetImpressionCountRequest\x1a#.tracker.GetImpressionCountResponseB,Z*github.com/killiankopp/arago/tracker/protob\x06proto3"

var (
	file_proto_tracker_proto_rawDescOnce sync.Once
	file_proto_tracker_proto_rawDescData []byte
)

func file_proto_tracker_proto_rawDescGZIP() []byte {
	file_proto_tracker_proto_rawDescOnce.Do(func() {
		file_proto_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tracker_proto_rawDesc), len(file_proto_tracker_proto_rawDesc)))
	})
	return file_proto_tracker_proto_rawDescData
}

var file_proto_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tracker_proto_goTypes = []any{
	(*AdImpression)(nil),               // 0: tracker.AdImpression
	(*UpdateImpressionRequest)(nil),    // 1: tracker.UpdateImpressionRequest
	(*UpdateImpressionResponse)(nil),   // 2: tracker.UpdateImpressionResponse
	(*GetImpressionCountRequest)(nil),  // 3: tracker.GetImpressionCountRequest
	(*GetImpressionCountResponse)(nil), // 4: tracker.GetImpressionCountResponse
}
var file_proto_tracker_proto_depIdxs = []int32{
	1, // 0: tracker.TrackerService.UpdateImpression:input_type -> tracker.UpdateImpressionRequest
	3, // 1: tracker.TrackerService.GetImpressionCount:input_type -> tracker.GetImpressionCountRequest
	2, // 2: tracker.TrackerService.UpdateImpression:output_type -> tracker.UpdateImpressionResponse
	4, // 3: tracker.TrackerService.GetImpressionCount:output_type -> tracker.GetImpressionCountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tracker_proto_init() }
func file_proto_tracker_proto_init() {
	if File_proto_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tracker_proto_rawDesc), len(file_proto_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tracker_proto_goTypes,
		DependencyIndexes: file_proto_tracker_proto_depIdxs,
		MessageInfos:      file_proto_tracker_proto_msgTypes,
	}.Build()
	File_proto_tracker_proto = out.File
	file_proto_tracker_proto_goTypes = nil
	file_proto_tracker_proto_depIdxs = nil
}
